Fix a logic bug in slot allocation within LvmtStore
Conflux-Chain/cfx-storage2 pull request #16
Opened 2024-12-27 08:53 UTC by rongma7

## Summary
This PR fixes a bug in the slot allocation logic within the `commit` function of `LvmtStore`.

## Bug Description
The original logic processed each key in the `changes` parameter sequentially. If a key required a slot allocation, it would find the first slot not present in the `slot_alloc_view` (i.e., an immutable reference to the database) and allocate it to that key. Importantly, the database is not updated during this process. As a result, this approach may lead to multiple keys in the `changes` receiving the same slot allocation, which is incorrect.

## Solution
The updated logic excludes slots occupied by keys that have already been processed in the `changes` parameter (tracked by `cached_allocations`) after finding the first available slot not in the `slot_alloc_view`. This prevents multiple keys from being allocated the same slot.

- The logic for finding the first unallocated slot based on `slot_alloc_view` remains unchanged and is still handled within the `allocate_version_slot` function.
- The new logic to resolve allocation conflicts is implemented in a newly introduced function, `resolve_allocation_slot`, which is called by the `allocate_version_slot` function to ensure that `allocate_version_slot` has complete functionality for allocating correct slots.

Additionally, a related but separate change addresses the correctness of `resolve_allocation_slot`, which relies on there being no duplicate keys; otherwise, it will allocate different slots to the same key. Since having no duplicate keys is a requirement, an error `DuplicateKeysInOneCommit` has been added to return promptly if duplicate keys are encountered in the input parameter `changes`.

## Conclusion
These modifications correct the slot allocation logic by ensuring that each key receives a unique slot.

2024-12-27 10:50 UTC, ChenxingLi requested changes
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/16)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @rongma7)

___
*[`src/lvmt/storage.rs` line 137 at r1](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/16#-OF6ff_6-SimqOrRHIS-:-OF6ff_6-SimqOrRHIS0:b-r4sppy) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/491cbcda9329e71cec116b162792e9c4892fd5b1/src/lvmt/storage.rs#L137)):*
> ```XML
> }
> 
> fn resolve_allocation_slot(
> ```

The current implementation is very weird. In the earlier loop rounds, you directly access the DB, but in the final round, you access the cache. Maybe it's logically correct, but it’s no different from code that only works because of a bug.

Inappropriate logical structure also leads to a significant amount of duplicated code, with the repeated part being the complex LVMT slot allocation logic. This reduces code readability and increases the difficulty of future maintenance.

Consider merging `&db` and `cache` into a single object, and use the `get` method of this object to replace the original `db.get`, similar to how the Conflux-Rust EVM state accesses storage. This is a typical read-through write-back cache policy, and the current implementation exposes a lack of fundamental knowledge.


<!-- Sent from Reviewable.io -->

2024-12-27 10:52 UTC, ChenxingLi requested changes
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/16)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @rongma7)

___
*[`src/lvmt/storage.rs` line 58 at r3](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/16#-OF6j_kw5iDHgVzj3RG9:-OF6j_kw5iDHgVzj3RGA:ba998uf) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/491cbcda9329e71cec116b162792e9c4892fd5b1/src/lvmt/storage.rs#L58)):*
> ```XML
>         for (key, value) in changes {
>             if !set_of_keys.insert(key.clone()) {
>                 return Err(StorageError::DuplicateKeysInOneCommit);
> ```

I think we can just skip the duplicated keys, or panic. 


<!-- Sent from Reviewable.io -->

2024-12-30 08:28 UTC, rongma7 reviewed
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/16)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ChenxingLi)

___
*[`src/lvmt/storage.rs` line 137 at r1](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/16#-OF6ff_6-SimqOrRHIS-:-OFLfb7AChU0fN901XNg:b-896fix) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/491cbcda9329e71cec116b162792e9c4892fd5b1/src/lvmt/storage.rs#L137)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

The current implementation is very weird. In the earlier loop rounds, you directly access the DB, but in the final round, you access the cache. Maybe it's logically correct, but it’s no different from code that only works because of a bug.

Inappropriate logical structure also leads to a significant amount of duplicated code, with the repeated part being the complex LVMT slot allocation logic. This reduces code readability and increases the difficulty of future maintenance.

Consider merging `&db` and `cache` into a single object, and use the `get` method of this object to replace the original `db.get`, similar to how the Conflux-Rust EVM state accesses storage. This is a typical read-through write-back cache policy, and the current implementation exposes a lack of fundamental knowledge.
</blockquote></details>

Done.
___
*[`src/lvmt/storage.rs` line 58 at r3](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/16#-OF6j_kw5iDHgVzj3RG9:-OFLfahrDwAUyQqCTsIK:b-896fix) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/491cbcda9329e71cec116b162792e9c4892fd5b1/src/lvmt/storage.rs#L58)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

I think we can just skip the duplicated keys, or panic.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-30 09:34 UTC, ChenxingLi requested changes
> Reviewed 1 of 1 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/16)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @rongma7)

___
*[`src/lvmt/storage.rs` line 122 at r4](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/16#-OFLuF6G8FDnRzXMcQTM:-OFLuF6G8FDnRzXMcQTN:bvu26ye) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/ff9495d4197498d7151c9d21e9cebc711229ab6f/src/lvmt/storage.rs#L122)):*
> ```XML
>     }
> 
>     fn set_cache(&mut self, amt_node_id: AmtNodeId, alloc_info: AllocationKeyInfo) {
> ```

rename to `set`
___
*[`src/lvmt/storage.rs` line 124 at r4](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/16#-OFLuWR9Cp13LNwNVoV-:-OFLuWR9Cp13LNwNVoV0:b8jrv3f) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/ff9495d4197498d7151c9d21e9cebc711229ab6f/src/lvmt/storage.rs#L124)):*
> ```XML
>     fn set_cache(&mut self, amt_node_id: AmtNodeId, alloc_info: AllocationKeyInfo) {
>         self.cache.insert(amt_node_id, alloc_info);
>     }
> ```

Implement `commit` to `WriteSchema` in this PR. 


<!-- Sent from Reviewable.io -->

2024-12-30 09:45 UTC, rongma7 reviewed
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/16)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @ChenxingLi)

___
*[`src/lvmt/storage.rs` line 122 at r4](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/16#-OFLuF6G8FDnRzXMcQTM:-OFLvlkXCwJMnY8Ce8rX:b-896fix) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/ff9495d4197498d7151c9d21e9cebc711229ab6f/src/lvmt/storage.rs#L122)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

rename to `set`
</blockquote></details>

Done.
___
*[`src/lvmt/storage.rs` line 124 at r4](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/16#-OFLuWR9Cp13LNwNVoV-:-OFLx8xK30MgIjEAHHtr:b-896fix) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/ff9495d4197498d7151c9d21e9cebc711229ab6f/src/lvmt/storage.rs#L124)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

Implement `commit` to `WriteSchema` in this PR.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-30 11:04 UTC, ChenxingLi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/16)* status: 1 of 3 files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2024-12-31 05:39 UTC, ChenxingLi reviewed
> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/16)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @rongma7)



<!-- Sent from Reviewable.io -->

2024-12-31 05:39 UTC, ChenxingLi approved these changes
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/16)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rongma7)



<!-- Sent from Reviewable.io -->

2024-12-31 06:36 UTC, merged